interface ExplainRequestBody {
  question: string;
  options: { id: string; text: string; isCorrect: boolean }[];
  selectedOptionId?: string | null;
  cardId?: string;
  mode?: "quick" | "deep";
  fallbackExplanation?: string;
}

interface Env {
  ZAI_API_KEY?: string;
  ZAI_BASE_URL?: string;
}

// In-memory cache at edge isolate
const explanationCache = new Map<string, { explanation: string; model: string }>();

async function callZaiModel(
  baseUrl: string,
  apiKey: string,
  model: string,
  systemPrompt: string,
  userPrompt: string,
  maxTokens = 350
) {
  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      max_tokens: maxTokens,
      temperature: 0.2,
    }),
    signal: AbortSignal.timeout(4500),
  });

  const data: any = await res.json();
  if (!res.ok || data.error) {
    const errorMsg = data.error?.message || `HTTP ${res.status}`;
    const errorCode = data.error?.code || res.status;
    throw new Error(`Z.ai Error (${errorCode}): ${errorMsg}`);
  }

  let text = data.choices?.[0]?.message?.content?.trim();
  if (!text && data.choices?.[0]?.message?.reasoning_content) {
    text = data.choices[0].message.reasoning_content.trim();
  }

  if (!text) {
    throw new Error(`No text generated by ${model}`);
  }

  // Strip <think> tags
  text = text.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();

  // If model output analysis / drafting steps, extract the final draft or explanation
  const draftMatch = text.match(/(?:\*+Draft(?:\s*\d+)?:?\*+|(?:\*+Final Answer:?\*+))\s*([^\n][\s\S]*)/i);
  if (draftMatch && draftMatch[1]) {
    text = draftMatch[1].replace(/\n\s*\*+\s*\*+(?:Word Count|Constraint|Punchiness|Check)[\s\S]*/i, "").trim();
  }

  // Strip analysis preambles and prompt echoes
  text = text
    .replace(/^(?:(?:\d+\.\s*)?\*\*(?:Analyze|Analysis|Thinking|Reasoning|Planning)[^\n]*\*\*[\s\S]*?(?:\n\n|\n(?=[A-Z])))/i, "")
    .replace(/^(?:User asked|The user asks|Question|Prompt):[^\n]*\n?/gim, "")
    .replace(/^(?:Options|Choices):[^\n]*\n?/gim, "")
    .replace(/^(?:Correct Answer|Selected Option):[^\n]*\n?/gim, "")
    .trim();

  return text;
}

export async function onRequestPost(context: { request: Request; env: Env }) {
  const { request, env } = context;

  const ZAI_API_KEY =
    env.ZAI_API_KEY || "4d174dfe61744b749e7ee3820d80fa3f.rUgjgJ9aAOSrS7Us";
  const ZAI_BASE_URL = env.ZAI_BASE_URL || "https://api.z.ai/api/paas/v4";

  const corsHeaders = {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };

  try {
    const body: ExplainRequestBody = await request.json();
    const { question, options, selectedOptionId, cardId, mode = "quick", fallbackExplanation } = body;

    if (!question || !options || options.length === 0) {
      return new Response(
        JSON.stringify({ success: false, error: "Missing required fields: question and options" }),
        { status: 400, headers: corsHeaders }
      );
    }

    // Unique per-question cache key
    const cacheKey = `${cardId || "card"}__${question.trim().slice(0, 60)}__${selectedOptionId || "none"}__${mode}`;
    if (explanationCache.has(cacheKey)) {
      const cached = explanationCache.get(cacheKey)!;
      return new Response(
        JSON.stringify({
          success: true,
          explanation: cached.explanation,
          model: cached.model,
          cached: true,
        }),
        { status: 200, headers: corsHeaders }
      );
    }

    const correctOpt = options.find((o) => o.isCorrect) || options[0];
    const chosenOpt = selectedOptionId ? options.find((o) => o.id === selectedOptionId) : null;
    const isUserCorrect = chosenOpt?.isCorrect ?? false;

    const optionsList = options
      .map((o) => `[${o.id}] ${o.text}${o.isCorrect ? " (Correct)" : ""}`)
      .join(", ");

    let systemPrompt = "";
    let userPrompt = "";
    const primaryModel = mode === "deep" ? "glm-5.3-flash" : "glm-4.7-flash";
    const backupModels = mode === "deep" 
      ? ["glm-4.7-flash", "glm-4.5-flash"] 
      : ["glm-4.5-flash", "glm-5.3-flash"];
    const maxTokens = mode === "deep" ? 600 : 250;

    if (mode === "deep") {
      systemPrompt =
        "You are a friendly, clear technical tutor. Explain in simple, crystal-clear language that anyone can grasp quickly:\n" +
        "### 💡 Simple Concept\nIn 2 simple sentences, explain the core idea of why the correct answer is right.\n\n" +
        "### 🎯 Why Other Options Don't Work\n1 short, simple bullet point for each incorrect option.\n\n" +
        "### ⚡ Quick Memory Trick\nA short 1-line rule or mnemonic to easily remember this.\n\n" +
        "RULES:\n" +
        "- Keep it simple, clear, and strictly under 85 words total.\n" +
        "- NEVER use Markdown tables or ASCII matrices. Use only bullet points and bold text.\n" +
        "- NEVER repeat or echo the question, options, reasoning steps, or draft steps. Start directly with ### 💡 Simple Concept.";

      userPrompt =
        `Question: ${question}\n` +
        `Options: ${optionsList}\n` +
        `Correct Answer: [${correctOpt.id}] ${correctOpt.text}\n` +
        (chosenOpt ? `User Selected: [${chosenOpt.id}] ${chosenOpt.text} (${isUserCorrect ? "Correct" : "Incorrect"})\n` : "") +
        (fallbackExplanation ? `Context Details: ${fallbackExplanation}\n` : "");
    } else {
      systemPrompt =
        "You are a concise exam tutor. In 1-2 punchy sentences, explain why the correct option is right. " +
        "If the user chose incorrectly, briefly explain why. " +
        "Keep it strictly under 45 words, direct, clear, and beginner-friendly.\n" +
        "CRITICAL: Output ONLY the final explanation. Do NOT output any analysis, reasoning steps, drafting steps, or word counts. Never repeat the question or options. Start directly with the explanation.";

      userPrompt =
        `Question: ${question}\n` +
        `Options: ${optionsList}\n` +
        `Correct Answer: [${correctOpt.id}] ${correctOpt.text}\n` +
        (chosenOpt ? `User Selected: [${chosenOpt.id}] ${chosenOpt.text} (${isUserCorrect ? "Correct" : "Incorrect"})` : "");
    }

    let explanationText = "";
    let usedModel = primaryModel;
    let modelSuccess = false;

    // Try primary model
    try {
      explanationText = await callZaiModel(
        ZAI_BASE_URL,
        ZAI_API_KEY,
        primaryModel,
        systemPrompt,
        userPrompt,
        maxTokens
      );
      modelSuccess = true;
    } catch (primaryErr) {
      console.warn(`Primary model ${primaryModel} failed:`, primaryErr);

      // Try backup models in order
      for (const backup of backupModels) {
        try {
          explanationText = await callZaiModel(
            ZAI_BASE_URL,
            ZAI_API_KEY,
            backup,
            systemPrompt,
            userPrompt,
            maxTokens
          );
          usedModel = backup;
          modelSuccess = true;
          break;
        } catch (secErr) {
          console.warn(`Backup model ${backup} failed:`, secErr);
        }
      }
    }

    if (!modelSuccess) {
      // Clean fallbackExplanation: strip any "Option X:" or "Option [X] (text) is correct"
      let cleanFallback = fallbackExplanation ? fallbackExplanation.trim() : "";
      cleanFallback = cleanFallback
        .replace(/^Option\s+[A-D]:\s*/i, "")
        .replace(/^Option\s+\[[A-D]\]\s*\([^)]+\)\s*(?:is correct\.?)?\s*/i, "")
        .trim();

      if (!cleanFallback || cleanFallback.toLowerCase() === correctOpt.text.toLowerCase()) {
        cleanFallback = `**${correctOpt.text}** is the correct answer because it directly satisfies "${question.trim()}".`;
      }

      if (mode === "deep") {
        const wrongOpts = options.filter((o) => !o.isCorrect);
        explanationText =
          `### 💡 Core Concept\n**[${correctOpt.id}] ${correctOpt.text}** is correct. ${cleanFallback}\n\n` +
          `### 🎯 Why Other Options Don't Work\n` +
          wrongOpts.map((o) => `- **[${o.id}] ${o.text}**: Does not satisfy this question's requirements.`).join("\n") +
          `\n\n### ⚡ Quick Memory Trick\nAssociate **"${question.slice(0, 45).replace(/"/g, '')}..."** directly with **${correctOpt.text}**.`;
      } else {
        explanationText = cleanFallback;
      }
      usedModel = "offline-fallback";
    }

    if (usedModel !== "offline-fallback") {
      explanationCache.set(cacheKey, { explanation: explanationText, model: usedModel });
    }

    return new Response(
      JSON.stringify({
        success: true,
        explanation: explanationText,
        model: usedModel,
        cached: false,
      }),
      { status: 200, headers: corsHeaders }
    );
  } catch (err: any) {
    return new Response(
      JSON.stringify({ success: false, error: err?.message || "Internal error generating explanation" }),
      { status: 500, headers: corsHeaders }
    );
  }
}

export async function onRequestOptions() {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
}
