import { NextRequest, NextResponse } from "next/server";

interface ExplainRequestBody {
  question: string;
  options: { id: string; text: string; isCorrect: boolean }[];
  selectedOptionId?: string | null;
  cardId?: string;
  mode?: "quick" | "deep";
  fallbackExplanation?: string;
}

// In-memory cache to prevent burning tokens on duplicate requests
const explanationCache = new Map<string, { explanation: string; model: string }>();

const ZAI_API_KEY =
  process.env.ZAI_API_KEY || "4d174dfe61744b749e7ee3820d80fa3f.rUgjgJ9aAOSrS7Us";
const ZAI_BASE_URL = process.env.ZAI_BASE_URL || "https://api.z.ai/api/paas/v4";

async function callZaiModel(model: string, systemPrompt: string, userPrompt: string, maxTokens = 350) {
  const res = await fetch(`${ZAI_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${ZAI_API_KEY}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      max_tokens: maxTokens,
      temperature: 0.2,
    }),
    signal: AbortSignal.timeout(25000),
  });

  const data = await res.json();
  if (!res.ok || data.error) {
    const errorMsg = data.error?.message || `HTTP ${res.status}`;
    const errorCode = data.error?.code || res.status;
    throw new Error(`Z.ai Error (${errorCode}): ${errorMsg}`);
  }

  let text = data.choices?.[0]?.message?.content?.trim();
  // Fallback to reasoning_content if content was truncated or populated in thinking
  if (!text && data.choices?.[0]?.message?.reasoning_content) {
    text = data.choices[0].message.reasoning_content.trim();
  }

  if (!text) {
    throw new Error(`No text generated by ${model}`);
  }

  return text;
}

export async function POST(req: NextRequest) {
  try {
    const body: ExplainRequestBody = await req.json();
    const { question, options, selectedOptionId, cardId, mode = "quick", fallbackExplanation } = body;

    if (!question || !options || options.length === 0) {
      return NextResponse.json(
        { success: false, error: "Missing required fields: question and options" },
        { status: 400 }
      );
    }

    // Check in-memory cache
    const cacheKey = `${cardId || question}_${selectedOptionId || "none"}_${mode}`;
    if (explanationCache.has(cacheKey)) {
      const cached = explanationCache.get(cacheKey)!;
      return NextResponse.json({
        success: true,
        explanation: cached.explanation,
        model: cached.model,
        cached: true,
      });
    }

    const correctOpt = options.find((o) => o.isCorrect) || options[0];
    const chosenOpt = selectedOptionId ? options.find((o) => o.id === selectedOptionId) : null;
    const isUserCorrect = chosenOpt?.isCorrect ?? false;

    const optionsList = options
      .map((o) => `[${o.id}] ${o.text}${o.isCorrect ? " (Correct)" : ""}`)
      .join(", ");

    let systemPrompt = "";
    let userPrompt = "";
    const primaryModel = mode === "deep" ? "glm-5.3-flash" : "glm-4.7-flash";
    const backupModel = mode === "deep" ? "glm-4.7-flash" : "glm-5.3-flash";
    const maxTokens = mode === "deep" ? 850 : 350;

    if (mode === "deep") {
      systemPrompt =
        "You are an expert exam tutor. Provide an in-depth, structured explanation in clean Markdown:\n" +
        "### Core Concept\nExplain the underlying rule, principle, or mechanism of why the correct answer is right.\n\n" +
        "### Option Analysis\nExplain why each distractor choice is incorrect or what it actually represents.\n\n" +
        "### Key Takeaway / Mnemonic\nA quick, memorable rule or tip for exam day.\n\n" +
        "Keep it punchy, technical, and high-yield. Do not include conversational greetings.";

      userPrompt =
        `Question: ${question}\n` +
        `Options: ${optionsList}\n` +
        `Correct Answer: [${correctOpt.id}] ${correctOpt.text}\n` +
        (chosenOpt ? `User Selected: [${chosenOpt.id}] ${chosenOpt.text} (${isUserCorrect ? "Correct" : "Incorrect"})\n` : "") +
        (fallbackExplanation ? `Context Details: ${fallbackExplanation}\n` : "");
    } else {
      systemPrompt =
        "You are a concise exam tutor. In 1-2 punchy sentences, explain why the correct option is right. " +
        "If the user chose incorrectly, briefly point out why their choice is wrong. " +
        "Keep it strictly under 50 words, direct, and high-yield. No conversational filler.";

      userPrompt =
        `Question: ${question}\n` +
        `Options: ${optionsList}\n` +
        `Correct Answer: [${correctOpt.id}] ${correctOpt.text}\n` +
        (chosenOpt ? `User Selected: [${chosenOpt.id}] ${chosenOpt.text} (${isUserCorrect ? "Correct" : "Incorrect"})` : "");
    }

    let explanationText = "";
    let usedModel = primaryModel;

    try {
      // Attempt primary model (GLM 5.3 Flash for deep, GLM 4.7 Flash for quick)
      explanationText = await callZaiModel(primaryModel, systemPrompt, userPrompt, maxTokens);
    } catch (primaryErr) {
      console.warn(`Primary model ${primaryModel} failed:`, primaryErr instanceof Error ? primaryErr.message : primaryErr);

      // Failover to backup flash model
      try {
        usedModel = backupModel;
        explanationText = await callZaiModel(backupModel, systemPrompt, userPrompt, maxTokens);
      } catch (secondaryErr) {
        console.error(`Backup model ${backupModel} also failed:`, secondaryErr instanceof Error ? secondaryErr.message : secondaryErr);

        if (mode === "deep") {
          explanationText =
            `### Core Concept\nOption **[${correctOpt.id}] ${correctOpt.text}** is the correct answer.\n\n` +
            (fallbackExplanation ? `### Context Note\n${fallbackExplanation}\n\n` : "") +
            `### Key Takeaway\nReview this topic in the Spaced Repetition queue to reinforce the core pattern.`;
        } else {
          explanationText =
            fallbackExplanation ||
            `Option [${correctOpt.id}] (${correctOpt.text}) is the correct answer.`;
        }
        usedModel = "offline-fallback";
      }
    }

    // IMPORTANT: Only cache successful AI responses so transient errors don't permanently poison the cache!
    if (usedModel !== "offline-fallback") {
      explanationCache.set(cacheKey, { explanation: explanationText, model: usedModel });
    }

    return NextResponse.json({
      success: true,
      explanation: explanationText,
      model: usedModel,
      cached: false,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Internal error generating explanation";
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
