import { NextRequest, NextResponse } from "next/server";

interface ExplainRequestBody {
  question: string;
  options: { id: string; text: string; isCorrect: boolean }[];
  selectedOptionId?: string | null;
  cardId?: string;
  mode?: "quick" | "deep";
  fallbackExplanation?: string;
}

// In-memory cache to prevent burning tokens on duplicate requests
const explanationCache = new Map<string, { explanation: string; model: string }>();

const ZAI_API_KEY =
  process.env.ZAI_API_KEY || "4d174dfe61744b749e7ee3820d80fa3f.rUgjgJ9aAOSrS7Us";
const ZAI_BASE_URL = process.env.ZAI_BASE_URL || "https://api.z.ai/api/paas/v4";

async function callZaiModel(model: string, systemPrompt: string, userPrompt: string, maxTokens = 350) {
  const res = await fetch(`${ZAI_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${ZAI_API_KEY}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      max_tokens: maxTokens,
      temperature: 0.2,
    }),
    signal: AbortSignal.timeout(8000),
  });

  const data = await res.json();
  if (!res.ok || data.error) {
    const errorMsg = data.error?.message || `HTTP ${res.status}`;
    const errorCode = data.error?.code || res.status;
    throw new Error(`Z.ai Error (${errorCode}): ${errorMsg}`);
  }

  let text = data.choices?.[0]?.message?.content?.trim();
  // Fallback to reasoning_content if content was truncated or populated in thinking
  if (!text && data.choices?.[0]?.message?.reasoning_content) {
    text = data.choices[0].message.reasoning_content.trim();
  }

  if (!text) {
    throw new Error(`No text generated by ${model}`);
  }

  // Strip think tags, prompt echoes, or question headers if the model repeated them
  text = text
    .replace(/^<think>[\s\S]*?<\/think>/gi, "")
    .replace(/^(?:User asked|The user asks|Question|Prompt):[^\n]*\n?/gim, "")
    .replace(/^(?:Options|Choices):[^\n]*\n?/gim, "")
    .replace(/^(?:Correct Answer|Selected Option):[^\n]*\n?/gim, "")
    .trim();

  return text;
}

export async function POST(req: NextRequest) {
  try {
    const body: ExplainRequestBody = await req.json();
    const { question, options, selectedOptionId, cardId, mode = "quick", fallbackExplanation } = body;

    if (!question || !options || options.length === 0) {
      return NextResponse.json(
        { success: false, error: "Missing required fields: question and options" },
        { status: 400 }
      );
    }

    // Unique per-question cache key to prevent any state leakage between different cards
    const cacheKey = `${cardId || "card"}__${question.trim().slice(0, 60)}__${selectedOptionId || "none"}__${mode}`;
    if (explanationCache.has(cacheKey)) {
      const cached = explanationCache.get(cacheKey)!;
      return NextResponse.json({
        success: true,
        explanation: cached.explanation,
        model: cached.model,
        cached: true,
      });
    }

    const correctOpt = options.find((o) => o.isCorrect) || options[0];
    const chosenOpt = selectedOptionId ? options.find((o) => o.id === selectedOptionId) : null;
    const isUserCorrect = chosenOpt?.isCorrect ?? false;

    const optionsList = options
      .map((o) => `[${o.id}] ${o.text}${o.isCorrect ? " (Correct)" : ""}`)
      .join(", ");

    let systemPrompt = "";
    let userPrompt = "";
    const primaryModel = mode === "deep" ? "glm-5.3-flash" : "glm-4.7-flash";
    const backupModels = mode === "deep" 
      ? ["glm-4.7-flash", "glm-4.5-flash"] 
      : ["glm-4.5-flash", "glm-5.3-flash"];
    const maxTokens = mode === "deep" ? 600 : 250;

    if (mode === "deep") {
      systemPrompt =
        "You are a friendly, clear technical tutor. Explain in simple, crystal-clear language that anyone can grasp quickly:\n" +
        "### 💡 Simple Concept\nIn 2 simple sentences, explain the core idea of why the correct answer is right.\n\n" +
        "### 🎯 Why Other Options Don't Work\n1 short, simple bullet point for each incorrect option.\n\n" +
        "### ⚡ Quick Memory Trick\nA short 1-line rule or mnemonic to easily remember this.\n\n" +
        "RULES:\n" +
        "- Keep it simple, clear, and strictly under 85 words total.\n" +
        "- NEVER use Markdown tables or ASCII matrices. Use only bullet points and bold text.\n" +
        "- NEVER repeat or echo the question or options. Start directly with ### 💡 Simple Concept.";

      userPrompt =
        `Question: ${question}\n` +
        `Options: ${optionsList}\n` +
        `Correct Answer: [${correctOpt.id}] ${correctOpt.text}\n` +
        (chosenOpt ? `User Selected: [${chosenOpt.id}] ${chosenOpt.text} (${isUserCorrect ? "Correct" : "Incorrect"})\n` : "") +
        (fallbackExplanation ? `Context Details: ${fallbackExplanation}\n` : "");
    } else {
      systemPrompt =
        "You are a concise exam tutor. In 1-2 punchy sentences, explain why the correct option is right. " +
        "If the user chose incorrectly, briefly explain why. " +
        "Keep it strictly under 45 words, direct, clear, and beginner-friendly.\n" +
        "CRITICAL: Never repeat the question or options. Start directly with the explanation.";

      userPrompt =
        `Question: ${question}\n` +
        `Options: ${optionsList}\n` +
        `Correct Answer: [${correctOpt.id}] ${correctOpt.text}\n` +
        (chosenOpt ? `User Selected: [${chosenOpt.id}] ${chosenOpt.text} (${isUserCorrect ? "Correct" : "Incorrect"})` : "");
    }

    let explanationText = "";
    let usedModel = primaryModel;
    let modelSuccess = false;

    // Try primary model first
    try {
      explanationText = await callZaiModel(primaryModel, systemPrompt, userPrompt, maxTokens);
      modelSuccess = true;
    } catch (primaryErr) {
      console.warn(`Primary model ${primaryModel} failed:`, primaryErr instanceof Error ? primaryErr.message : primaryErr);

      // Try backup models in order
      for (const backup of backupModels) {
        try {
          explanationText = await callZaiModel(backup, systemPrompt, userPrompt, maxTokens);
          usedModel = backup;
          modelSuccess = true;
          break;
        } catch (secErr) {
          console.warn(`Backup model ${backup} failed:`, secErr instanceof Error ? secErr.message : secErr);
        }
      }
    }

    if (!modelSuccess) {
      if (mode === "deep") {
        const wrongOpts = options.filter((o) => !o.isCorrect);
        explanationText =
          `### 💡 Simple Concept\nOption **[${correctOpt.id}] ${correctOpt.text}** is the correct answer. ${fallbackExplanation || ""}\n\n` +
          `### 🎯 Why Other Options Don't Work\n` +
          wrongOpts.map((o) => `- **[${o.id}] ${o.text}**: Incorrect for this question.`).join("\n") +
          `\n\n### ⚡ Quick Memory Trick\nRemember: **[${correctOpt.id}]** directly matches the required pattern.`;
      } else {
        explanationText =
          fallbackExplanation ||
          `Option [${correctOpt.id}] (${correctOpt.text}) is the correct answer.`;
      }
      usedModel = "offline-fallback";
    }

    // Only cache successful AI responses so transient errors don't permanently poison the cache
    if (usedModel !== "offline-fallback") {
      explanationCache.set(cacheKey, { explanation: explanationText, model: usedModel });
    }

    return NextResponse.json({
      success: true,
      explanation: explanationText,
      model: usedModel,
      cached: false,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Internal error generating explanation";
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
